name: Healthwise
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  camera: ^0.9.4+1
  tflite: ^1.1.2
  cloud_firestore: ^4.0.5
  firebase_core: ^2.2.0
  firebase_storage: ^11.0.5
  flutter_icons: 1.1.0
  # flutter_native_splash: ^2.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.17


flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/SVG/

flutter_native_splash:
  image: assets/SVG/logo.png
  color: FFC0CB



  
